[package]
name = "rsomics-help"
version = "0.4.0"
description = "Unified command-line interaction and presentation for rsomics products"
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"
repository = "https://github.com/omics-rust/rsomics-help"
authors = ["Zane Leong <efd@live.com>"]
categories = ["command-line-interface"]
keywords = ["help", "cli", "clap", "terminal", "bioinformatics"]
readme = "README.md"

[dependencies]
clap = { version = "4", features = ["color", "derive", "error-context", "help", "std", "suggestions", "usage", "wrap_help"] }
